[package]
name = "phantom_agents"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.sncast]
account = "phantom_deployer"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.public.blastapi.io"